### ISSUE TITLE
Blast contig results

### ISSUE THREAD

**Issue by tthye1** [oschwengers/platon#26] opened 2021-12-27 19:53 UTC
Hi,
thanks for developing Platon. I have run Platon to identify contigs of a specific plasmid (pESI).
Some of the identified contigs have 100% identity with several different plasmids, but platon only reports the first one of the blast list.
Is there a way to report all blast results of the contigs which have identical identity.

Best,

Thorsten

**Comment by oschwengers** [comment] 2022-01-05 16:52
Hi Thorsten,
thanks for reporting. Platon does not actively select the single best hit but reports all hits with a coverage and identity of 80%.
Could you provide an example where Platon fails to report 2 eligible hits?

**Comment by tthye1** [comment] 2022-01-06 08:05
Hi,

please find attached a plasmid.fasta file where the first 3 sequences I analysed with blast resulted in several hits with 100% coverage and identity.

Best,

Thorsten

[CLA2_S14__out.1.contigs.plasmid.fasta.txt](https://github.com/oschwengers/platon/files/7820323/CLA2_S14__out.1.contigs.plasmid.fasta.txt)
[CLA2_S14__out.1.contigs Kopie.log](https://github.com/oschwengers/platon/files/7820326/CLA2_S14__out.1.contigs.Kopie.log)

**Comment by oschwengers** [comment] 2022-01-06 09:02
and to which other plasmid sequences? I'm asking to exclude cases with hits to several sequences from the same plasmid family that might be de-duplicated within refseq.

**Comment by tthye1** [comment] 2022-01-06 10:56
I provide this example. A Blast analyses of Contig  „contig00199“  resulted in several plasmids with identical coverage. I think the identified plasmids are very similar but not the same. For my analysis I need the list of all identical identified plasmids.

Best Thorsten

Best,

Thorsten

**Comment by oschwengers** [comment] 2022-01-07 09:59
Could you provide a detailed example with all relevant information to reproduce this behavior?
- Query sequence: contig00199
- Target plasmid sequences: full list of identified plasmids with accession numbers?
- For each target plasmid: subject coverage and sequence identity values?
- Which plasmid database has been used?

Otherwise, I don't know which plasmid sequences should be found. 

Also, I think this is maybe out of scope for Platon since hits to "all" identical plasmid sequences do not provide more useful information regarding the actual chrom/plas classification. However, if you mean identical *hits* to reference plasmids then I fully agree.

**Comment by oschwengers** [comment] 2022-03-29 06:48
Hi @tthye1 ,
is this still active? Otherwise, I'd close this for now.

**Comment by tthye1** [comment] 2022-03-29 06:56
Hi,

Please close it.

Best

**Closed** 2022-03-29 07:02 UTC
Labels: enhancement
