### ISSUE TITLE
execution problem

### ISSUE THREAD

**Issue by kimTina321** [oschwengers/platon#41] opened 2023-08-05 04:18 UTC
- what exact command was executed: just copy-paste the command line
   platon -h
- what installation of Platon did you use: `BioConda`, `GitHub`, `Pip`
 I used mamba install

- what exactly happened
  Traceback (most recent call last):
  File "/home/liu/.local/bin/platon", line 5, in <module>
    from platon.platon import main
  File "/home/liu/.local/lib/python3.10/site-packages/platon/platon.py", line 12, in <module>
    from Bio import SeqIO
  File "/home/liu/.local/lib/python3.9/site-packages/Bio/SeqIO/__init__.py", line 374, in <module>
    from Bio.Align import MultipleSeqAlignment
  File "/home/liu/.local/lib/python3.9/site-packages/Bio/Align/__init__.py", line 29, in <module>
    raise MissingPythonDependencyError(
Bio.MissingPythonDependencyError: Please install numpy if you want to use Bio.Align. See http://www.numpy.org

But there's numpy 1.25.2 in this conda environment, and I also create a new environment for platon.

**Comment by oschwengers** [comment] 2023-08-11 07:26
Hi @kimTina321 ,
I tested Platon v1.7.0 in a fresh conda environment and database via:
```
mamba create -p ./conda platon=1.7.0
wget https://zenodo.org/record/4066768/files/db.tar.gz
tar -xzf db.tar.gz
platon --db ./db --prefix test --output test --verbose test-genome.fna
```
It ran smoothly without any error or issue.

**Comment by kimTina321** [comment] 2023-08-17 08:49
> Hi @kimTina321 , I tested Platon v1.7.0 in a fresh conda environment and database via:
> 
> ```
> mamba create -p ./conda platon=1.7.0
> wget https://zenodo.org/record/4066768/files/db.tar.gz
> tar -xzf db.tar.gz
> platon --db ./db --prefix test --output test --verbose test-genome.fna
> ```
> 
> It ran smoothly without any error or issue.

Hi, @oschwengers . I ran what you did, but I still met the error message below. Sorry for bothering you again. Besides, I tried to download plasmidFinder before and met the similar error of numpy.

Traceback (most recent call last):
  File "/home/liu/conda/bin/platon", line 6, in <module>
    from platon.platon import main
  File "/home/liu/conda/lib/python3.11/site-packages/platon/platon.py", line 12, in <module>
    from Bio import SeqIO
  File "/home/liu/.local/lib/python3.9/site-packages/Bio/SeqIO/__init__.py", line 374, in <module>
    from Bio.Align import MultipleSeqAlignment
  File "/home/liu/.local/lib/python3.9/site-packages/Bio/Align/__init__.py", line 29, in <module>
    raise MissingPythonDependencyError(
Bio.MissingPythonDependencyError: Please install numpy if you want to use Bio.Align. See http://www.numpy.org/

**Comment by oschwengers** [comment] 2023-08-28 09:38
I'm sorry, I cannot reproduce this error. It seems like you have a mixture of different Python versions within your Conda environment: Python 3.11 and 3.9 what should not be the case.

As this is not related to Platon but the Conda setup, may I kindly refer you the the official Conda / Bioconda docs?
Therefore, I'll close this now but please, do not hesitate to re-open it or a new issue in any case.
Thanks and kind regards!

**Closed by oschwengers** 2023-08-28 09:38 UTC
Labels: help wanted
